// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NtoboaFund.Data.DBContext;

namespace NtoboaFund.Migrations
{
    [DbContext(typeof(NtoboaFundDbContext))]
    [Migration("20210922110945_changed donor to donation")]
    partial class changeddonortodonation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<decimal>("Points");

                    b.Property<string>("PreferedMoneyReceptionMethod");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Token");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int>("UserType");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.BankDetails", b =>
                {
                    b.Property<string>("BankDetailsId");

                    b.Property<string>("AccountNumber");

                    b.Property<string>("BankName");

                    b.Property<string>("SwiftCode");

                    b.HasKey("BankDetailsId");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("AmountToWin");

                    b.Property<string>("Date");

                    b.Property<string>("DateDeclared");

                    b.Property<string>("Period");

                    b.Property<string>("Status");

                    b.Property<int?>("TransferId");

                    b.Property<string>("TxRef");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("Name");

                    b.Property<string>("Reason");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.CrowdFund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<string>("EndDate");

                    b.Property<string>("MainImageUrl");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("SecondImageUrl");

                    b.Property<string>("ThirdImageUrl");

                    b.Property<string>("Title");

                    b.Property<decimal>("TotalAmount");

                    b.Property<decimal>("TotalAmountRecieved");

                    b.Property<int>("TypeId");

                    b.Property<string>("UserId");

                    b.Property<string>("videoUrl");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("CrowdFunds");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.CrowdFundType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CrowdFundTypes");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountDonated");

                    b.Property<int>("CrowdFundId");

                    b.Property<int>("UserId");

                    b.Property<bool>("paid");

                    b.Property<decimal>("txRef");

                    b.HasKey("Id");

                    b.HasIndex("CrowdFundId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.LuckyMe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("AmountToWin");

                    b.Property<string>("Date");

                    b.Property<string>("DateDeclared");

                    b.Property<string>("Period");

                    b.Property<string>("Status");

                    b.Property<int?>("TransferId");

                    b.Property<string>("TxRef");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LuckyMes");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.MobileMoneyDetails", b =>
                {
                    b.Property<string>("MobileMoneyDetailsId");

                    b.Property<string>("Country");

                    b.Property<string>("Currency");

                    b.Property<string>("Network");

                    b.Property<string>("Number");

                    b.Property<string>("Voucher");

                    b.HasKey("MobileMoneyDetailsId");

                    b.ToTable("MobileMoneyDetails");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatePayed");

                    b.Property<bool>("IsPaid");

                    b.Property<string>("ItemPayedFor");

                    b.Property<int>("ItemPayedForId");

                    b.Property<string>("PayerId");

                    b.Property<long>("TransactionId");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Scholarship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("AmountToWin");

                    b.Property<string>("Date");

                    b.Property<string>("DateDeclared");

                    b.Property<string>("Institution")
                        .IsRequired();

                    b.Property<string>("Period");

                    b.Property<string>("PlayerType")
                        .IsRequired();

                    b.Property<string>("Program")
                        .IsRequired();

                    b.Property<string>("Status");

                    b.Property<string>("StudentId")
                        .IsRequired();

                    b.Property<int?>("TransferId");

                    b.Property<string>("TxRef");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Scholarships");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Transfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account_number");

                    b.Property<int>("amount");

                    b.Property<string>("bank_code");

                    b.Property<string>("bank_name");

                    b.Property<string>("complete_message");

                    b.Property<string>("currency");

                    b.Property<DateTime>("date_created");

                    b.Property<int>("fee");

                    b.Property<string>("fullname");

                    b.Property<int>("id");

                    b.Property<int>("is_approved");

                    b.Property<string>("message");

                    b.Property<string>("narration");

                    b.Property<string>("reference");

                    b.Property<int>("requires_approval");

                    b.Property<string>("status");

                    b.HasKey("TransferId");

                    b.ToTable("Transfer");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.UserBuilder", b =>
                {
                    b.Property<int>("UserBuilderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("UserBuilderId");

                    b.ToTable("UserBuilders");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.UssdSession", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientState");

                    b.Property<string>("SessionId");

                    b.HasKey("Id");

                    b.ToTable("UssdSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.BankDetails", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser", "User")
                        .WithOne("BankDetails")
                        .HasForeignKey("NtoboaFund.Data.Models.BankDetails", "BankDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Business", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser", "User")
                        .WithMany("Businesses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.CrowdFund", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.CrowdFundType", "CrowdFundType")
                        .WithMany("CrowdFunds")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser", "User")
                        .WithMany("CrowdFunds")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Donation", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.CrowdFund", "CrowdFund")
                        .WithMany("Donations")
                        .HasForeignKey("CrowdFundId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.LuckyMe", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser", "User")
                        .WithMany("LuckyMes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.MobileMoneyDetails", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser", "User")
                        .WithOne("MomoDetails")
                        .HasForeignKey("NtoboaFund.Data.Models.MobileMoneyDetails", "MobileMoneyDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NtoboaFund.Data.Models.Scholarship", b =>
                {
                    b.HasOne("NtoboaFund.Data.Models.ApplicationUser", "User")
                        .WithMany("Scholarships")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
